---
abstract: 'Allows use of Module::Build and ExtUtils::MakeMaker in a dzil dist'
author:
  - 'Apocalypse <APOCAL@cpan.org>'
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-DualBuilders
provides:
  Dist::Zilla::Plugin::DualBuilders:
    file: lib/Dist/Zilla/Plugin/DualBuilders.pm
    version: 0.01
requires:
  Dist::Zilla::Role::PrereqSource: 2.101170
  Moose: 1.01
  Moose::Util::TypeConstraints: 1.01
  Test::More: 0.94
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Dist-Zilla-Plugin-DualBuilders
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-DualBuilders
  license: http://dev.perl.org/licenses/
  repository: http://github.com/apocalypse/perl-dist-zilla-plugin-dualbuilders
version: 0.01
